//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.33440.
// 
namespace WA.Master.Address.Correction {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://www.doh.wa.gov/gis")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetstandardizedaddressOperationCompleted;
        
        /// <remarks/>
        public Service() {
            string urlSetting = System.Configuration.ConfigurationManager.AppSettings["CorrectionUrl"];
            if ((urlSetting != null)) {
                this.Url = string.Concat(urlSetting, "addresscorrection_v2/service.asmx");
            }
            else {
                this.Url = "http://geoservicestest.wa.gov/addresscorrection_v2/service.asmx";
            }
        }
        
        /// <remarks/>
        public event GetstandardizedaddressCompletedEventHandler GetstandardizedaddressCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.doh.wa.gov/gis/Getstandardizedaddress", RequestNamespace="http://www.doh.wa.gov/gis", ResponseNamespace="http://www.doh.wa.gov/gis", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Address_Correction Getstandardizedaddress(string address, string address2, string city, string company, string zip, string state, string zip4) {
            object[] results = this.Invoke("Getstandardizedaddress", new object[] {
                        address,
                        address2,
                        city,
                        company,
                        zip,
                        state,
                        zip4});
            return ((Address_Correction)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetstandardizedaddress(string address, string address2, string city, string company, string zip, string state, string zip4, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Getstandardizedaddress", new object[] {
                        address,
                        address2,
                        city,
                        company,
                        zip,
                        state,
                        zip4}, callback, asyncState);
        }
        
        /// <remarks/>
        public Address_Correction EndGetstandardizedaddress(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Address_Correction)(results[0]));
        }
        
        /// <remarks/>
        public void GetstandardizedaddressAsync(string address, string address2, string city, string company, string zip, string state, string zip4) {
            this.GetstandardizedaddressAsync(address, address2, city, company, zip, state, zip4, null);
        }
        
        /// <remarks/>
        public void GetstandardizedaddressAsync(string address, string address2, string city, string company, string zip, string state, string zip4, object userState) {
            if ((this.GetstandardizedaddressOperationCompleted == null)) {
                this.GetstandardizedaddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetstandardizedaddressOperationCompleted);
            }
            this.InvokeAsync("Getstandardizedaddress", new object[] {
                        address,
                        address2,
                        city,
                        company,
                        zip,
                        state,
                        zip4}, this.GetstandardizedaddressOperationCompleted, userState);
        }
        
        private void OnGetstandardizedaddressOperationCompleted(object arg) {
            if ((this.GetstandardizedaddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetstandardizedaddressCompleted(this, new GetstandardizedaddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.doh.wa.gov/gis")]
    public partial class Address_Correction {
        
        private string input_AddressField;
        
        private string input_Address2Field;
        
        private string input_CompanyField;
        
        private string input_MunicipalJurisdictionField;
        
        private string input_ZipCodeField;
        
        private string input_ZipPlus4Field;
        
        private string input_StateNameField;
        
        private string addressField;
        
        private string address2Field;
        
        private string companyField;
        
        private string garbageField;
        
        private string addressTypeField;
        
        private string municipalJurisdictionField;
        
        private string zipCodeField;
        
        private string zipPlus4Field;
        
        private string stateNameField;
        
        private string countyField;
        
        private string preDirectionalField;
        
        private string numberField;
        
        private string streetNameField;
        
        private string preTypeField;
        
        private string postSuffixField;
        
        private string postDirectionalField;
        
        private string unitField;
        
        private string unitTypeField;
        
        private string foundField;
        
        private string qualityField;
        
        private string resultsField;
        
        private string errorStatusField;
        
        private string candidate1Field;
        
        private string candidate2Field;
        
        private string candidate3Field;
        
        private string candidate4Field;
        
        private string candidate5Field;
        
        private string addresskeyField;
        
        /// <remarks/>
        public string input_Address {
            get {
                return this.input_AddressField;
            }
            set {
                this.input_AddressField = value;
            }
        }
        
        /// <remarks/>
        public string input_Address2 {
            get {
                return this.input_Address2Field;
            }
            set {
                this.input_Address2Field = value;
            }
        }
        
        /// <remarks/>
        public string input_Company {
            get {
                return this.input_CompanyField;
            }
            set {
                this.input_CompanyField = value;
            }
        }
        
        /// <remarks/>
        public string input_MunicipalJurisdiction {
            get {
                return this.input_MunicipalJurisdictionField;
            }
            set {
                this.input_MunicipalJurisdictionField = value;
            }
        }
        
        /// <remarks/>
        public string input_ZipCode {
            get {
                return this.input_ZipCodeField;
            }
            set {
                this.input_ZipCodeField = value;
            }
        }
        
        /// <remarks/>
        public string input_ZipPlus4 {
            get {
                return this.input_ZipPlus4Field;
            }
            set {
                this.input_ZipPlus4Field = value;
            }
        }
        
        /// <remarks/>
        public string input_StateName {
            get {
                return this.input_StateNameField;
            }
            set {
                this.input_StateNameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public string Garbage {
            get {
                return this.garbageField;
            }
            set {
                this.garbageField = value;
            }
        }
        
        /// <remarks/>
        public string AddressType {
            get {
                return this.addressTypeField;
            }
            set {
                this.addressTypeField = value;
            }
        }
        
        /// <remarks/>
        public string MunicipalJurisdiction {
            get {
                return this.municipalJurisdictionField;
            }
            set {
                this.municipalJurisdictionField = value;
            }
        }
        
        /// <remarks/>
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ZipPlus4 {
            get {
                return this.zipPlus4Field;
            }
            set {
                this.zipPlus4Field = value;
            }
        }
        
        /// <remarks/>
        public string StateName {
            get {
                return this.stateNameField;
            }
            set {
                this.stateNameField = value;
            }
        }
        
        /// <remarks/>
        public string County {
            get {
                return this.countyField;
            }
            set {
                this.countyField = value;
            }
        }
        
        /// <remarks/>
        public string PreDirectional {
            get {
                return this.preDirectionalField;
            }
            set {
                this.preDirectionalField = value;
            }
        }
        
        /// <remarks/>
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public string StreetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
            }
        }
        
        /// <remarks/>
        public string PreType {
            get {
                return this.preTypeField;
            }
            set {
                this.preTypeField = value;
            }
        }
        
        /// <remarks/>
        public string PostSuffix {
            get {
                return this.postSuffixField;
            }
            set {
                this.postSuffixField = value;
            }
        }
        
        /// <remarks/>
        public string PostDirectional {
            get {
                return this.postDirectionalField;
            }
            set {
                this.postDirectionalField = value;
            }
        }
        
        /// <remarks/>
        public string Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        public string UnitType {
            get {
                return this.unitTypeField;
            }
            set {
                this.unitTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Found {
            get {
                return this.foundField;
            }
            set {
                this.foundField = value;
            }
        }
        
        /// <remarks/>
        public string Quality {
            get {
                return this.qualityField;
            }
            set {
                this.qualityField = value;
            }
        }
        
        /// <remarks/>
        public string Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorStatus {
            get {
                return this.errorStatusField;
            }
            set {
                this.errorStatusField = value;
            }
        }
        
        /// <remarks/>
        public string Candidate1 {
            get {
                return this.candidate1Field;
            }
            set {
                this.candidate1Field = value;
            }
        }
        
        /// <remarks/>
        public string Candidate2 {
            get {
                return this.candidate2Field;
            }
            set {
                this.candidate2Field = value;
            }
        }
        
        /// <remarks/>
        public string Candidate3 {
            get {
                return this.candidate3Field;
            }
            set {
                this.candidate3Field = value;
            }
        }
        
        /// <remarks/>
        public string Candidate4 {
            get {
                return this.candidate4Field;
            }
            set {
                this.candidate4Field = value;
            }
        }
        
        /// <remarks/>
        public string Candidate5 {
            get {
                return this.candidate5Field;
            }
            set {
                this.candidate5Field = value;
            }
        }
        
        /// <remarks/>
        public string Addresskey {
            get {
                return this.addresskeyField;
            }
            set {
                this.addresskeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void GetstandardizedaddressCompletedEventHandler(object sender, GetstandardizedaddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetstandardizedaddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetstandardizedaddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Address_Correction Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Address_Correction)(this.results[0]));
            }
        }
    }
}
