//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.33440.
// 
namespace WA.Master.Address.Geocoder {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GeocoderSoap", Namespace="http://geography.wa.gov/GeospatialPortal/")]
    public partial class Geocoder : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback FindAddressOperationCompleted;
        
        /// <remarks/>
        public Geocoder() {
            string urlSetting = System.Configuration.ConfigurationManager.AppSettings["GeocoderUrl"];
            if ((urlSetting != null)) {
                this.Url = string.Concat(urlSetting, "geocoder_v2/service.asmx");
            }
            else {
                this.Url = "http://geoservicestest.wa.gov/geocoder_v2/service.asmx";
            }
        }
        
        /// <remarks/>
        public event FindAddressCompletedEventHandler FindAddressCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://geography.wa.gov/GeospatialPortal/FindAddress", RequestNamespace="http://geography.wa.gov/GeospatialPortal/", ResponseNamespace="http://geography.wa.gov/GeospatialPortal/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Geocode FindAddress(string address, string zip, string city, string zip4, string AddressKey) {
            object[] results = this.Invoke("FindAddress", new object[] {
                        address,
                        zip,
                        city,
                        zip4,
                        AddressKey});
            return ((Geocode)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginFindAddress(string address, string zip, string city, string zip4, string AddressKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FindAddress", new object[] {
                        address,
                        zip,
                        city,
                        zip4,
                        AddressKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public Geocode EndFindAddress(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Geocode)(results[0]));
        }
        
        /// <remarks/>
        public void FindAddressAsync(string address, string zip, string city, string zip4, string AddressKey) {
            this.FindAddressAsync(address, zip, city, zip4, AddressKey, null);
        }
        
        /// <remarks/>
        public void FindAddressAsync(string address, string zip, string city, string zip4, string AddressKey, object userState) {
            if ((this.FindAddressOperationCompleted == null)) {
                this.FindAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindAddressOperationCompleted);
            }
            this.InvokeAsync("FindAddress", new object[] {
                        address,
                        zip,
                        city,
                        zip4,
                        AddressKey}, this.FindAddressOperationCompleted, userState);
        }
        
        private void OnFindAddressOperationCompleted(object arg) {
            if ((this.FindAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindAddressCompleted(this, new FindAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geography.wa.gov/GeospatialPortal/")]
    public partial class Geocode {
        
        private string input_addressField;
        
        private string input_zipField;
        
        private string input_municipaljurisdictionField;
        
        private string input_zip4Field;
        
        private string input_addresskeyField;
        
        private string statusField;
        
        private string scoreField;
        
        private string sourceField;
        
        private string accuracyField;
        
        private string longitudeField;
        
        private string latitudeField;
        
        private string av_dateField;
        
        private string error_statusField;
        
        /// <remarks/>
        public string input_address {
            get {
                return this.input_addressField;
            }
            set {
                this.input_addressField = value;
            }
        }
        
        /// <remarks/>
        public string input_zip {
            get {
                return this.input_zipField;
            }
            set {
                this.input_zipField = value;
            }
        }
        
        /// <remarks/>
        public string input_municipaljurisdiction {
            get {
                return this.input_municipaljurisdictionField;
            }
            set {
                this.input_municipaljurisdictionField = value;
            }
        }
        
        /// <remarks/>
        public string input_zip4 {
            get {
                return this.input_zip4Field;
            }
            set {
                this.input_zip4Field = value;
            }
        }
        
        /// <remarks/>
        public string input_addresskey {
            get {
                return this.input_addresskeyField;
            }
            set {
                this.input_addresskeyField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
            }
        }
        
        /// <remarks/>
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public string accuracy {
            get {
                return this.accuracyField;
            }
            set {
                this.accuracyField = value;
            }
        }
        
        /// <remarks/>
        public string longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public string latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public string Av_date {
            get {
                return this.av_dateField;
            }
            set {
                this.av_dateField = value;
            }
        }
        
        /// <remarks/>
        public string error_status {
            get {
                return this.error_statusField;
            }
            set {
                this.error_statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void FindAddressCompletedEventHandler(object sender, FindAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Geocode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Geocode)(this.results[0]));
            }
        }
    }
}
